@startuml
skinparam classAttributeIconSize 0
class Employee{
- id:int=0
- name:String
#depertoment:String
/連続年数:int
---
+setid(id:int):void
+getid():int
+setname(name:String):void
+getName(name:String):void
+setdept(dept:String):void
+getdept():String
}
hide Employee circle
@enduml
例）
「従業員」クラスの「勤続年数」は「入社年月日」と
現在の日付から計算が可能なので、派生属性とな
ります。
図派生属性