@startuml 診察予約システム
[*] -right-> メニュー
メニュー --> 予約と確認画面
予約と確認画面 --> メニュー
予約と確認画面 --right--> あなたの順番
予約と確認画面 --right--> あなたの順番
あなたの順番 -down-> メニュー
メニュー -down-> 今の順番
現在の順番 -down-> メニュー
メニュー -right->[*]
@enduml